name: 🐞 Bug Report
description: Use this form to report bugs found in Hynix.
title: "[BUG]: "
labels:
  - bug
  - triage
assignees:
  - lucasaugustsof
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in Hynix!
        Please fill out the information below so we can understand and fix the issue effectively.

  - type: input
    id: bug_title
    attributes:
      label: Bug Title
      description: Provide a brief and descriptive title for the issue.
      placeholder: Primary button does not apply hover in dark mode
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Explain the issue in detail. Include what happened, what you expected to happen, and any relevant context.
      placeholder: Describe the issue, including steps to reproduce, expected vs. actual behavior, and any additional information.
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment Details
      description: Specify the environment where the bug occurred (browser, OS, framework version, etc.).
      placeholder: Chrome 109, Windows 10, TailwindCSS 4.0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity of the Bug
      description: Indicate the impact of the bug on the functionality of Hynix.
      options:
        - Critical - Prevents use of the system
        - High - Significant impact, but there are alternatives
        - Medium - Moderate impact
        - Low - Minimal impact
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Navigate to...
        2. Click on...
        3. Observe the following...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe how the system should behave if the bug were fixed.
      placeholder: The primary button should change color on hover in dark mode.
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe the behavior currently observed.
      placeholder: The primary button does not change color on hover in dark mode.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Thank you for your contribution!**
        The Hynix team will review your issue promptly and provide updates.
