name: 🧩 Component Request
description: Request the creation of a new component for the Hynix Design System.
title: "[COMPONENT]: "
labels:
  - UI
  - enhancement
  - triage
assignees:
  - lucasaugustsof
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new component for Hynix!
        Please fill out the information below to help us understand and prioritize your request.

  - type: input
    id: component_name
    attributes:
      label: Component Name
      description: Provide the name of the component you want to request.
      placeholder: Card, Tooltip, Avatar
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Component Description
      description: Explain the purpose and functionality of the component.
      placeholder: |
        A Card component that displays information in a container, with options for an image, title, and text.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe how and where the component will be used in the application.
      placeholder: |
        The Card component will be used for displaying product listings in an e-commerce interface.
    validations:
      required: true

  - type: textarea
    id: design_references
    attributes:
      label: Design References
      description: Share links or examples that could inspire the design of the component.
      placeholder: |
        Reference - https://tailwindui.com/components/application-ui/cards

  - type: dropdown
    id: complexity
    attributes:
      label: Component Complexity
      description: Indicate the expected complexity level for the component.
      options:
        - Low (Simple, with minimal styling and basic functionality)
        - Medium (Moderate, with multiple variants and customizations)
        - High (Complex, with dynamic or interactive behavior)
    validations:
      required: true

  - type: textarea
    id: required_variants
    attributes:
      label: Required Variants
      description: Specify any variants for the component, such as sizes, styles, or themes.
      placeholder: |
        "Example: Small, Medium, Large or Primary, Secondary, Destructive."

  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility Requirements
      description: Describe any accessibility requirements for the component.
      placeholder: |
        "Example: The component must support keyboard navigation, screen readers, and sufficient contrast."

  - type: textarea
    id: api_spec
    attributes:
      label: API Specification
      description: List the properties or APIs the component should support. Include examples if possible.
      placeholder: |
        "Example:
         - `title` (string): The title text of the card.
         - `image` (URL): The image source for the card.
         - `onClick` (function): A callback function for click events."

  - type: markdown
    attributes:
      value: |
        **Thank you for your contribution!**
        The Hynix team will review your request and provide updates soon.
