name: 📝 Documentation Suggestion
description: Propose improvements or new content for Hynix documentation.
title: "[DOCS]: "
labels: ["documentation", "enhancement", "triage"]
assignees:
  - lucasaugustsof
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting improvements to the Hynix documentation!
        Please fill out the information below to help us understand your suggestion.

  - type: input
    id: section
    attributes:
      label: Documentation Section
      description: Which part of the documentation does your suggestion refer to?
      placeholder: "Components", "Getting Started", "API Reference"
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: Briefly describe your improvement or addition suggestion.
      placeholder: "Add usage example for Button component with icons."
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: Explain how this change will help users.
      placeholder: "Will make it easier to implement the Button component with icon support."
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful (examples, references, etc.).
      placeholder: "Similar documentation patterns from other libraries or frameworks."
      required: false

  - type: file
    id: attachments
    attributes:
      label: Attachments
      description: Optional. Upload screenshots, diagrams, or other files to support your suggestion.
      multiple: true

  - type: markdown
    attributes:
      value: |
        **Thank you for your contribution!**
        The Hynix team will review your suggestion soon.
