export enum InitPreflightWarning {
  ALREADY_INITIALIZED = 'ALREADY_INITIALIZED',
  MISSING_PEER_DEPENDENCIES = 'MISSING_PEER_DEPENDENCIES',
  INCOMPATIBLE_TAILWIND_VERSION = 'INCOMPATIBLE_TAILWIND_VERSION',
}

export enum InitPreflightError {
  MISSING_PACKAGE_JSON = 'MISSING_PACKAGE_JSON',
}
